[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.6.6'

# 如果需要为不同的合约使用不同的编译器版本，可以使用以下配置
[profile.default.model_checker]
contracts = { 'src/v2/**/*.sol' = { solc = '0.6.6' } }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
